# Generated by Django 5.2.11 on 2026-02-25 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_group_created_at_alter_expense_paid_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'Groups'},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group'], name='core_expens_group_i_10c184_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['paid_by'], name='core_expens_paid_by_94515f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group', 'created_at'], name='core_expens_group_i_7256dd_idx'),
        ),
    ]
